<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Locators.Runtime</AssemblyName>
    <RootNamespace>SkeletonKey.Locators.Runtime</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Locators\SkeletonKey.Locators.csproj" />
    <ProjectReference Include="..\SkeletonKey.Workflow\SkeletonKey.Workflow.csproj" />
  </ItemGroup>
</Project>
