<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>skeletonkey</AssemblyName>
    <RootNamespace>SkeletonKey.Runner</RootNamespace>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Runner.Core\SkeletonKey.Runner.Core.csproj" />
  </ItemGroup>
</Project>
