<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Runtime.Invocation</AssemblyName>
    <RootNamespace>SkeletonKey.Runtime.Invocation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Workflow\SkeletonKey.Workflow.csproj" />
  </ItemGroup>
</Project>
