<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Runtime.Interactions</AssemblyName>
    <RootNamespace>SkeletonKey.Runtime.Interactions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Abstractions\SkeletonKey.Abstractions.csproj" />
  </ItemGroup>
</Project>
