<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Handlers</AssemblyName>
    <RootNamespace>SkeletonKey.Handlers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Abstractions\SkeletonKey.Abstractions.csproj" />
    <ProjectReference Include="..\SkeletonKey.Catalog\SkeletonKey.Catalog.csproj" />
    <ProjectReference Include="..\SkeletonKey.Execution\SkeletonKey.Execution.csproj" />
  </ItemGroup>
</Project>
