<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Web.BuiltIns</AssemblyName>
    <RootNamespace>SkeletonKey.Web.BuiltIns</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Catalog\SkeletonKey.Catalog.csproj" />
    <ProjectReference Include="..\SkeletonKey.Execution\SkeletonKey.Execution.csproj" />
    <ProjectReference Include="..\SkeletonKey.Handlers\SkeletonKey.Handlers.csproj" />
    <ProjectReference Include="..\SkeletonKey.Artifacts\SkeletonKey.Artifacts.csproj" />
    <ProjectReference Include="..\SkeletonKey.Locators\SkeletonKey.Locators.csproj" />
    <ProjectReference Include="..\SkeletonKey.Web.Abstractions\SkeletonKey.Web.Abstractions.csproj" />
    <ProjectReference Include="..\SkeletonKey.Workflow\SkeletonKey.Workflow.csproj" />
  </ItemGroup>
</Project>
