<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Web.BuiltIns.Tests</AssemblyName>
    <RootNamespace>SkeletonKey.Web.BuiltIns.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SkeletonKey.Catalog.Validation\SkeletonKey.Catalog.Validation.csproj" />
    <ProjectReference Include="..\..\src\SkeletonKey.Locators.Runtime\SkeletonKey.Locators.Runtime.csproj" />
    <ProjectReference Include="..\..\src\SkeletonKey.Web.BuiltIns\SkeletonKey.Web.BuiltIns.csproj" />
  </ItemGroup>
</Project>
