<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkeletonKey.Runtime.Resources</AssemblyName>
    <RootNamespace>SkeletonKey.Runtime.Resources</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkeletonKey.Execution\SkeletonKey.Execution.csproj" />
    <ProjectReference Include="..\SkeletonKey.Workflow\SkeletonKey.Workflow.csproj" />
  </ItemGroup>
</Project>
